// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Services;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240522141904_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication2.Models.Bolum", b =>
                {
                    b.Property<int>("bolumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bolumID"));

                    b.Property<string>("bolumAd")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("fakulteID")
                        .HasColumnType("int");

                    b.HasKey("bolumID");

                    b.HasIndex("fakulteID");

                    b.ToTable("tBolum");
                });

            modelBuilder.Entity("WebApplication2.Models.Fakulte", b =>
                {
                    b.Property<int>("fakulteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("fakulteID"));

                    b.Property<string>("fakulteAd")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("fakulteID");

                    b.ToTable("tFakulte");
                });

            modelBuilder.Entity("WebApplication2.Models.Ogrenci", b =>
                {
                    b.Property<int>("ogrenciID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ogrenciID"));

                    b.Property<string>("ad")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("bolumID")
                        .HasColumnType("int");

                    b.Property<string>("soyad")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ogrenciID");

                    b.HasIndex("bolumID");

                    b.ToTable("tOgrenci");
                });

            modelBuilder.Entity("WebApplication2.Models.OgrenciDers", b =>
                {
                    b.Property<int>("ogrenciDersID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ogrenciDersID"));

                    b.Property<int>("dersID")
                        .HasColumnType("int");

                    b.Property<int>("final")
                        .HasColumnType("int");

                    b.Property<int>("ogrenciID")
                        .HasColumnType("int");

                    b.Property<int>("vize")
                        .HasColumnType("int");

                    b.Property<int>("yariyil")
                        .HasColumnType("int");

                    b.Property<int>("yil")
                        .HasColumnType("int");

                    b.HasKey("ogrenciDersID");

                    b.HasIndex("ogrenciID");

                    b.ToTable("tOgrenciDers");
                });

            modelBuilder.Entity("WebApplication2.Models.Bolum", b =>
                {
                    b.HasOne("WebApplication2.Models.Fakulte", "Fakulte")
                        .WithMany()
                        .HasForeignKey("fakulteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fakulte");
                });

            modelBuilder.Entity("WebApplication2.Models.Ogrenci", b =>
                {
                    b.HasOne("WebApplication2.Models.Bolum", "Bolum")
                        .WithMany()
                        .HasForeignKey("bolumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("WebApplication2.Models.OgrenciDers", b =>
                {
                    b.HasOne("WebApplication2.Models.Ogrenci", "Ogrenci")
                        .WithMany()
                        .HasForeignKey("ogrenciID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ogrenci");
                });
#pragma warning restore 612, 618
        }
    }
}
