create table CUSTOMERS
(
ID INT PRIMARY KEY NOT NULL,
USERNAME NVARCHAR(20) NOT NULL,
BIRTHDATE DATETIME NOT NULL,
ISMALE BIT NOT NULL,
ORDERPRICEAVERAGE DECIMAL(12,2) NULL
)
create table ORDERS
(
ORDERID INT PRIMARY KEY NOT NULL,
CUSTOMERID INT FOREIGN KEY REFERENCES CUSTOMERS NOT NULL,
PRODUCTNAME NVARCHAR(20) NOT NULL,
ORDERDATE DATETIME NOT NULL,
PRICE DECIMAL(12,2) NOT NULL,
ISSEND BIT NOT NULL
)
create table SUPPLIERS
(
ID INT PRIMARY KEY NOT NULL,
COMPANYNAME NVARCHAR(40) NOT NULL,
CREATIONDATE DATETIME NOT NULL,
SELLPRICEAVERAGE DECIMAL(12,2) NULL,
ISSELLING BIT NOT NULL
)
create table PRODUCTS
(
ID INT PRIMARY KEY NOT NULL,
PRODUCTNAME NVARCHAR(20) NOT NULL,
SUPPLIERID INT FOREIGN KEY REFERENCES SUPPLIERS NOT NULL,
PRICE DECIMAL(12,2) NOT NULL,
EXPIRATIONDATE DATETIME NOT NULL,
ISAVAILABLE BIT NOT NULL
)
create table DELIVERY
(
ID INT PRIMARY KEY NOT NULL,
ORDERID INT FOREIGN KEY REFERENCES ORDERS NOT NULL,
DDATE DATETIME NOT NULL,
DPERSON NVARCHAR(20) NOT NULL,
DISTANCE DECIMAL(12,2) NOT NULL,
ISDELIVERED BIT NOT NULL
)